// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwOcRp-JnOx9WsZf1aHdehtbWOP6FkfXY',
    appId: '1:803491436570:web:5e4b9cb658d57a9b2399a3',
    messagingSenderId: '803491436570',
    projectId: 'unityhub-afd87',
    authDomain: 'unityhub-afd87.firebaseapp.com',
    storageBucket: 'unityhub-afd87.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfF-3uLEZ5zod4HYxByCADJs5Lq78m820',
    appId: '1:803491436570:android:2d48808da9291beb2399a3',
    messagingSenderId: '803491436570',
    projectId: 'unityhub-afd87',
    storageBucket: 'unityhub-afd87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWDPFcsq-peQ8sbQ4_tb1it-I_ajU_8vc',
    appId: '1:803491436570:ios:f39953b51ed035d52399a3',
    messagingSenderId: '803491436570',
    projectId: 'unityhub-afd87',
    storageBucket: 'unityhub-afd87.firebasestorage.app',
    iosClientId: '803491436570-k626nijbo6ie5q7lkr7bso0onj173hll.apps.googleusercontent.com',
    iosBundleId: 'com.unityhub.unityhubMobile',
  );
}
